### ISSUE TITLE
Make button optional in the client-and-work section

### ISSUE THREAD

**Issue by lucaspal** [radity/raditian-free-hugo-theme#22]
**What**
Add the option to disable the button for each item in the `works` section under `client_and_work`.

**Why**
Sometimes there is simply no external resource to link. This simple change would cover this use case and make the section more flexible.

**Example:**
```
works:
    - title: "Radity Finance - UI Kit"
      description: "We have been receiving a lot of requests for a Finance Kit recently due to the popularity of Fintech."
      button:
        enabled: false
      image:
        x: "img/works/radity-finance.jpg"
        _2x: "img/works/radity-finance@2x.jpg"
      is_even: true
```
