### ISSUE TITLE
[Question] How hard will it be to add additional pages?

### ISSUE THREAD

**Issue by dtriana** [radity/raditian-free-hugo-theme#4]
I have successfully reused your theme for my son website, its looking great, however I'm planning to add some new content that will make more sense on its own page. It doesn't looks like the theme supports it, does it?

If it doesn't, how hard will it be to make it work for more pages?

Thanks!

**Comment by oaksakal** [comment]
thanks for using Raditian. We have designed the theme for single page concept. It could be extended for multipage. I will check within our team whether we could introduce this quickly. Depending on your tech saviness of course you can do it on your own as well. I will update the issue once I clarify internally.

**Comment by Hermsi1337** [comment]
@dtriana in case you need it fast - here's how to do it quick and dirty.

First, create the layout for your new single-pages:

`layouts/_default/single.html`:

```html
<!-- inject:../components/baseHead/baseHeadStart.html -->
<!DOCTYPE html>
<html lang="en">

<head>

    {{ partial "head.html" . }}

    {{ partial "head_custom.html" . }}

</head>

<body>

    {{ partial "header.html" . }}

    <section class="rad-single rad-animation-group rad-fade-down">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-8 col-lg-7 col-xl-6">
                    <p class="lead">
                        {{ .Content | safeHTML }}
                    </p>
                </div>
            </div>
        </div>
    </section>


    {{ partial "footer.html" . }}

    {{ partial "base-foot.html" . }}

</body>

</html>
<!-- endinject -->
```

Add the corresponding styles:

`static/css/custom.css`:
```css
/* single page header */
.rad-single {
    display: -webkit-box;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    flex-direction: column;
    -webkit-box-pack: center;
    justify-content: center;
    -webkit-box-align: center;
    align-items: center;
    position: relative;
    margin-bottom: -20px;
    padding-top: 80px;
}
```

Then, add your desired content:

`content/your_content.md`:

```markdown
---
title: "YourContent"
date: 2020-04-13T16:13:37+01:00
author: Hermsi1337
draft: false
---

CONTENT

---
```

In order to fix the title in your browser-tab, you may adapt the following change in the `head.html`:

```html
<title>{{ .Title | default "Home" }} | Hermsi1337</title>
```
